# Generated by Django 3.2a1 on 2021-11-22 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(max_length=50)),
                ('func_description', models.CharField(max_length=250)),
                ('hara_function', models.BooleanField(default=True)),
                ('hara_rationale', models.CharField(default='Enter rationale', max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('ANY', 'ANY LOCATION'), ('PRK', 'PARKING'), ('LOW', 'LOW SPEED ROAD'), ('MED', 'MEDIUM SPEED ROAD'), ('HIH', 'HIGH SPEED ROAD'), ('OFF', 'OFF ROAD'), ('INT', 'INTERSECTION'), ('WAS', 'CAR WASH'), ('REM', 'STRANDED'), ('VOT', 'VEHICLE ON TRANSPORT'), ('SER', 'VEHICLE ON SERVICE')], max_length=75)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='item_definition.function')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='function',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function', to='item_definition.item'),
        ),
    ]
