openapi: 3.0.2
info:
  title: API
  description: Description
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/beta
    description: Local
components:
  links:
  parameters:
  responses:
  schemas:
  securitySchemes:
security:
